// --------------------------------------------------------------------------------
// This is manually typed code
// --------------------------------------------------------------------------------
// import React from 'react';


// --------------------------------------------------------------------------------
// Create new class
// --------------------------------------------------------------------------------
// class MainComponent extends React.Component{
//     // render method
//     render() {
//         // return method
//         return(
//             <div>
//                 <h1>Hello World</h1>
//             </div>
//         );
//     }
// }

// export default MainComponent;

// --------------------------------------------------------------------------------
// This code generated by snippet
// snippet code - rcc
// --------------------------------------------------------------------------------
import React, { Component } from 'react'
import ItemBox from './ItemBox/ItemBox';

// -----------------------------------------------------------------------------------
// Import Image
// -----------------------------------------------------------------------------------
import ReactImage from '../Images/ItemBox/logo192.png'
import AngularImage from '../Images/ItemBox/Angular_full_color_logo.svg.png'
import VueImage from '../Images/ItemBox/58482acecef1014c0b5e4a1e.png'

export default class MainComponent extends Component {
    // Create Constructor
    constructor(props) {    // props = parameters / attributes
        super(props);

        // JavaScript Object
        this.state = {
            name: 'Rukshan',
            lastName: 'Nuwan'
        }
    }

    // Create a function
    changeName = () => {
        // setState = state eka use karala thiyana hema thenakama thiyana value eka update karanne setState eken.
        // E.g: this.state.lastName = 'Nuwan' update wenw 'Janaranjana' widiyata.
        this.setState(
            {
                lastName: 'Janaranjana'
            }
        )
    }

    render() {
        return (
            <div>
                <h1>Hello World</h1>
                <p>My name is {this.state.name} {this.state.lastName}</p>

                {/* ES6 */}
                <p>{`My name is ${this.state.name} ${this.state.lastName}`}</p>

                {/* Button */}
                <button onClick={this.changeName}>Change Last Name</button>

                <hr />

                <div style={{ display: 'flex', justifyContent: 'center' }}>
                    {/* ItemBox */}
                    <ItemBox title="React JS" version="17.0.1" description="React JS sample description" image={ReactImage} />
                    <ItemBox title="Angular" version="10.0.0" description="Angular sample description" image={AngularImage} />
                    <ItemBox title="Vue JS" version="3.0.0" description="Vue.js sample description" image={VueImage} />
                </div>
            </div>
        )
    }
}
